<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function ponto_import_theme(){
  $theme['ponto_import_start'] = [
    'variables' => ['form_action' => NULL],
    'template' => 'ponto_import_start'
  ];
  
  $theme['ponto_export_start'] = [
    'variables' => ['form_action' => NULL],
    'template' => 'ponto_export_start'
  ];
  
  return $theme;
}